package rules;

import com.ruoyi.iot.domain.Order;
import com.ruoyi.iot.domain.Alarm;
import com.ruoyi.iot.domain.Device;

rule "Identify alarm type"
when
    $alarm: Alarm()
    $device: Device()
    $order: Order()
then
        $alarm.setDeviceId($device.getId())
              .setAlarmPoint($order.getAlarmPoint())
              .setDeviceName($device.getDeviceName())
              .setDeviceIp($device.getDeviceIp())
              .setDeviceType($device.getDeviceType())
              .setSn($device.getSn())
              .setAlarmTypeId($order.getAlarmTypeId())
              .setAlarmType($order.getAlarmType())
              .setAlarmTime($order.getAlarmTime())
              .setAlarmCapture($order.getAlarmCapture())
              .setAlarmContent($order.getAlarmContent())
              .setRemark($order.getRemark())
              .setAlarmStatus(0);
end